# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release a version

on: 
  workflow_dispatch:
    inputs:
      scope:
        description: 'Scope: patch, minor, major'     
        required: true
        default: 'patch'
      stage:
        description: 'Stage: beta, final'     
        required: true
        default: 'beta'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish package
        run: ./gradlew api:publish reckonTagPush -Preckon.stage=${{ github.event.inputs.stage }} -Preckon.scope=${{ github.event.inputs.scope }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
