# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test it all

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Updated to v3
      with:
        fetch-depth: '0' # fetch-depth:0 is often for versioning tools, may not be strictly needed for 'verify' but doesn't hurt.
    - name: Set up JDK 1.8 and Maven
      uses: actions/setup-java@v3 # Updated to v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven' # Enable caching for Maven dependencies

    - name: Check tags
      run: echo  "Git tags:" $(git tag -l) # This step can be kept or removed

    - name: Test with Maven
      # The 'verify' phase runs all tests and other checks.
      # Using -B for non-interactive mode.
      run: mvn -B verify --file pom.xml
